### ISSUE TITLE
.listNodes() returns error

### ISSUE THREAD

**Issue by CACGaming** [FyreBlitz/pteroly#1]
**Describe the bug**
.listNodes() returns an error

**To Reproduce**
Try to use .listNodes()

**Expected behavior**
Gets node list

**Screenshots**

**Desktop (please complete the following information):**
Irrelevant

**Smartphone (please complete the following information):**
Irrelevant
**Additional context**
You didn't capitalize an L in application/methods/nodes/listNodes.js
    return Req.getRequest('listNodes', null, null);
should be
    return Req.getRequest('ListNodes', null, null);

**Comment by OnFire124** [comment]
Looking into it

**Comment by OnFire124** [comment]
Found the issue, I had a typo in the code. Thanks :)

**Comment by OnFire124** [comment]
v1.6.7 released.
