### ISSUE TITLE
Enviroment variables incorrects

### ISSUE THREAD

**Issue by felipe-negri** [FyreBlitz/pteroly#3]
in login method you use CLIENT_PTEROLY_HOST and CLIENT_PTEROLY_KEY variables
![Screenshot_20220223_195517](https://user-images.githubusercontent.com/27769172/155423328-3c5118cf-d516-4638-9223-ea2cfa547d36.png)
and in some methods you use CLIENT_NODEACTYL_HOST and process.env.CLIENT_NODEACTYL_KEY

![Screenshot_20220223_195718](https://user-images.githubusercontent.com/27769172/155423564-f8f96dec-cb66-4811-8879-495843c3f4d4.png)

this causes error on requests

**Comment by OnFire124** [comment]
Fixed that
